### ISSUE TITLE
Search window not visible if Map/Altas is open

### ISSUE THREAD

**Issue by r15ch13** [dydrmr/VerseTime#11]
## Problem:
The search window is not visible if the Map or the Altas is open.
The text input gets focused and Map/Atlas can only be closed by pressing `Escape`.

## Expected:
The search should be visible or close the others.

## Solutions:
1. Each window toggles the others off.
2. Search window opens above the others and update the view of Map/Atlas if the user selects a location.

**Comment by r15ch13** [comment]
Something like that:
![image](https://github.com/dydrmr/VerseTime/assets/432127/0e817bae-5223-481c-aafb-f1861a5f6a5a)

**Comment by dydrmr** [comment]
Implemented in build [711a9cb](https://github.com/dydrmr/VerseTime/commit/711a9cbc803beb33aae2210f3229069d62479069)
