### ISSUE TITLE
Firefox - Keyboard Search Issue

### ISSUE THREAD

**Issue by Paladinleeds** [dydrmr/VerseTime#13]
So, I've noticed that in VerseTime, you have `/` set as the keyboard shortcut to bring up the search bar. The problem is that in Firefox, that same keyboard shortcut is used to bring up the Quick Find menu within the browser. While I have noticed there is the workaround of clicking on the location to bring up that same menu, it does create a slightly inconsistent experience for Firefox users vs other browsers (I assume Edge and Chrome don't have that same keyboard shortcut).

**Comment by dydrmr** [comment]
Good catch! Thanks for letting me know. Should be fixed in commit aefa5a3.

**Comment by Paladinleeds** [comment]
Yep, that seems to have fixed it, though may be worth letting Firefox users know that behaviour is overridden.
